import { ContentPage } from "@/components/seo/ContentPage";

const TermsOfUse = () => (
  <ContentPage
    title="VISOR Terms of Use"
    description="The terms that govern your access to and use of the VISOR mobile app, AI features, community features and subscriptions, operated by Drakkar in Norway."
    path="/terms"
    h1="Terms of Use"
    breadcrumbs={[
      { label: "Home", href: "/" },
      { label: "Terms of Use", href: "/terms" },
    ]}
    intro={
      <>
        These Terms of Use govern your access to and use of the VISOR mobile application and related services,
        including fitness planning, nutrition tools, AI features, community features and subscriptions. VISOR is
        operated by Drakkar Mahmed Harun, a sole proprietorship registered in Norway. These Terms work together with our{" "}
        <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>.
        By downloading, creating an account for, or using VISOR, you agree to these Terms. If you do not agree, do not use the service.
        <br />
        <span className="text-sm opacity-70">Last updated: June 2026</span>
      </>
    }
    sections={[
      {
        heading: "Who We Are",
        body: (
          <p>
            VISOR is operated by <strong>Drakkar Mahmed Harun</strong>, a sole proprietorship
            (<em>enkeltpersonforetak</em>) registered in Norway under organisation number{" "}
            <strong>935 975 530</strong>, with registered address Bjørnegårdsvingen 17, 1338 Sandvika, Norway
            ("Drakkar", "VISOR", "we", "us"). "Drakkar" is used as the operating umbrella for the VISOR app.
          </p>
        ),
      },
      {
        heading: "Eligibility and Accounts",
        body: (
          <ul className="list-disc pl-5 space-y-2">
            <li>You must be at least 13 years old to use VISOR, or older if required by the laws where you live (for example, 16 in some EU/EEA countries). Where a higher age applies, you may use VISOR only with consent from a parent or guardian.</li>
            <li>If you are between 13 and 17, you confirm that you have permission from a parent or legal guardian to use VISOR and to allow us to process your fitness and health data. We may require verification of parental consent and may suspend or delete accounts where we reasonably believe a user is under 13, or where a minor's use raises a health or safety concern.</li>
            <li>You agree to provide accurate account information, including an accurate date of birth, and keep it reasonably up to date.</li>
            <li>You are responsible for maintaining the confidentiality of your login credentials and for activity that occurs through your account.</li>
          </ul>
        ),
      },
      {
        heading: "Health, Wellness, and AI Disclaimer",
        body: (
          <>
            <p>VISOR provides fitness, nutrition, wellness and motivational tools for general informational purposes only. VISOR is not a medical service and does not provide medical diagnosis or treatment.</p>
            <p>You should consult a qualified healthcare professional before starting or changing any exercise, nutrition, recovery or supplementation program, especially if you have an injury, medical condition or other health concern.</p>
            <p>Calorie and nutrition targets generated by VISOR are estimates for general wellness purposes only and are not individualized medical nutrition therapy. If you have or suspect an eating disorder, a history of disordered eating, or significant body-image concerns, do not rely on calorie targets or body-transformation features without first consulting a qualified healthcare or mental-health professional. These features are not designed to diagnose or treat any eating disorder.</p>
            <p>VISOR's calorie-tracking and nutrition features are <strong>not appropriate</strong> for anyone currently under medical supervision or treatment for an eating disorder (including anorexia, bulimia or binge-eating disorder) or any medically supervised dietary program. If this applies to you, consult your healthcare provider before using these features. If you are under 18, we strongly recommend involving a parent, guardian or healthcare professional in setting any calorie or body-composition goals.</p>
            <p>AI-generated outputs — including chat guidance, meal analysis, workout suggestions and body-transformation visuals — may be incomplete or inaccurate. They should not be treated as medical advice, safety clearance or guaranteed results. See "AI-Generated Content" below.</p>
          </>
        ),
      },
      {
        heading: "AI-Generated Content",
        body: (
          <>
            <p>VISOR includes AI-generated content — including coaching chat responses, meal-image analysis, workout suggestions and body-transformation visuals — produced with the help of third-party AI providers.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>AI-generated content is machine-produced and may be incomplete, inaccurate or inappropriate. It is not professional, medical, nutritional or psychological advice.</li>
              <li>Body-transformation visuals are AI-created illustrative simulations only, are labeled as AI-generated within the app, and do not represent medical predictions, promised results or realistic depictions of your future body. Individual results vary significantly.</li>
              <li>You can flag or report any AI output, post, message or community item you find objectionable, harmful, inaccurate or in violation of these Terms using the in-app report function, or by emailing privacy@visorfitness.com.</li>
              <li>We review reports and take appropriate action — including removing content or restricting accounts — and aim to respond within 5 business days.</li>
            </ul>
          </>
        ),
      },
      {
        heading: "Subscriptions, Trials, and Billing",
        body: (
          <ul className="list-disc pl-5 space-y-2">
            <li>VISOR may offer free and paid tiers, including auto-renewing subscriptions that unlock premium features.</li>
            <li>The subscription title, length of the subscription period, and the price are shown to you on the purchase screen before you confirm.</li>
            <li>Payment is charged to your Apple ID account at confirmation of purchase (on iOS) or to your Google Play account (on Android).</li>
            <li>Your subscription automatically renews unless auto-renew is turned off at least 24 hours before the end of the current period.</li>
            <li>Your account is charged for renewal within 24 hours prior to the end of the current period, at the price of the selected plan.</li>
            <li>You can manage or cancel your subscription and turn off auto-renew in your device account settings: on iOS, App Store &gt; your account &gt; Subscriptions; on Android, Google Play &gt; Subscriptions.</li>
            <li>Any free trial automatically converts to a paid subscription at the end of the trial period unless canceled beforehand; any unused portion of a free trial is forfeited when you purchase a subscription.</li>
            <li>For App Store purchases, <strong>Apple is the merchant of record</strong>; billing, refunds and cancellations are governed by Apple's Media Services Terms and Conditions, and VISOR cannot directly issue refunds for App Store purchases. Refunds are otherwise handled under the rules of the applicable app store unless required by law.</li>
          </ul>
        ),
      },
      {
        heading: "Right of Withdrawal (EU/EEA Consumers)",
        body: (
          <>
            <p>
              If you are a consumer in the EU/EEA, you normally have a 14-day right to withdraw from a purchase of digital
              services. By starting a subscription or accessing premium digital content immediately, you expressly request
              that performance begin during the withdrawal period and acknowledge that you lose the right of withdrawal once
              the service has been fully performed.
            </p>
            <p>
              Where billing is handled by Apple or Google, refunds and cancellations follow the applicable app store's
              rules, in addition to any mandatory consumer rights you have under Norwegian and EU/EEA law.
            </p>
          </>
        ),
      },
      {
        heading: "Community and User Content",
        body: (
          <>
            <p>If you post content, join groups, send messages or otherwise submit user content in VISOR, you are responsible for that content and for ensuring that you have the rights needed to share it.</p>
            <p>You grant VISOR a limited, non-exclusive, worldwide license to host, store, reproduce, display and process your user content only as reasonably necessary to operate, secure, moderate and improve the service.</p>
            <p>You can report illegal, infringing or objectionable content, or other violations, using the in-app report function on any post, message, AI output or community item, or by emailing privacy@visorfitness.com. We review reports and may remove content or restrict accounts that breach these Terms or applicable law, and aim to respond within 5 business days.</p>
          </>
        ),
      },
      {
        heading: "Acceptable Use",
        body: (
          <>
            <p>You must not use VISOR to break the law, harass others, impersonate another person, upload harmful or infringing content, or interfere with the security or operation of the service.</p>
            <p>You must not attempt to scrape, reverse engineer, decompile or misuse VISOR, its APIs, AI features or subscription systems except where a restriction is prohibited by applicable law.</p>
          </>
        ),
      },
      {
        heading: "Intellectual Property",
        body: <p>VISOR and its content, software, branding, workout media, designs and materials are owned by Drakkar or its licensors and are protected by applicable intellectual property laws.</p>,
      },
      {
        heading: "Service Availability and Changes",
        body: (
          <>
            <p>We may add, modify, suspend or remove features, content, pricing or parts of the service at any time.</p>
            <p>We work to keep VISOR available and functional, but we do not guarantee uninterrupted availability, perfect accuracy or that every feature will always remain available.</p>
          </>
        ),
      },
      {
        heading: "Suspension, Termination, and Deletion",
        body: (
          <>
            <p>We may suspend or terminate access to VISOR if we reasonably believe you violated these Terms, created risk for users or the platform, or used the service in a fraudulent or abusive way.</p>
            <p>You may stop using VISOR at any time. You can permanently delete your account at any time directly in the app, from your account settings, without needing to contact us.</p>
          </>
        ),
      },
      {
        heading: "Disclaimers and Liability Limits",
        body: (
          <p>
            To the fullest extent permitted by applicable law, VISOR is provided on an "as is" and "as available" basis without warranties of any kind, whether express or implied.
            To the fullest extent permitted by applicable law, VISOR will not be liable for indirect, incidental, special, consequential, exemplary or punitive damages, or for loss of data, profits, goodwill or business opportunities arising from your use of the service.
            Nothing in these Terms limits rights that cannot be waived under applicable consumer protection law, including mandatory Norwegian and EU/EEA consumer rights.
          </p>
        ),
      },
      {
        heading: "Changes to These Terms",
        body: <p>We may update these Terms from time to time. If we make material changes, we will notify you in-app, by email or by other appropriate means. Your continued use of VISOR after changes take effect means you accept the updated Terms.</p>,
      },
      {
        heading: "Governing Law and Disputes",
        body: (
          <>
            <p>
              These Terms are governed by the laws of Norway, without regard to conflict-of-law rules. Disputes are subject
              to the jurisdiction of the Norwegian courts.
            </p>
            <p>
              If you are a consumer, this does not deprive you of the protection of mandatory consumer law in your country of
              residence, and you may bring proceedings in your local courts where required by law. EU/EEA consumers may also
              use the European Commission's Online Dispute Resolution platform at{" "}
              <a href="https://ec.europa.eu/consumers/odr" className="text-primary hover:underline">ec.europa.eu/consumers/odr</a>.
            </p>
          </>
        ),
      },
      {
        heading: "Severability",
        body: <p>If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will continue in full force and effect.</p>,
      },
      {
        heading: "Contact Us",
        body: (
          <p>
            Operator: <strong>Drakkar Mahmed Harun</strong> (org. no. 935 975 530), Bjørnegårdsvingen 17, 1338 Sandvika, Norway
            <br />
            Website: <a href="https://visorfitness.com" className="text-primary hover:underline">visorfitness.com</a>
            <br />
            Email: <a href="mailto:privacy@visorfitness.com" className="text-primary hover:underline">privacy@visorfitness.com</a>
          </p>
        ),
      },
    ]}
  />
);

export default TermsOfUse;
